/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/breakingJar.glb -o components/GlassJar/BreakingJarooo1.js -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/breakingJar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial_cell.geometry} material={materials.material_1} position={[-4.626, 4.751, -1.33]} />
      <mesh geometry={nodes.defaultMaterial_cell001.geometry} material={materials.material_1} position={[4.165, 9.714, -2.75]} />
      <mesh geometry={nodes.defaultMaterial_cell002.geometry} material={materials.material_1} position={[2.974, 15.793, -1.382]} />
      <mesh geometry={nodes.defaultMaterial_cell003.geometry} material={materials.material_1} position={[3.838, 1.357, 1.459]} />
      <mesh geometry={nodes.defaultMaterial_cell004.geometry} material={materials.material_1} position={[4.611, 11.428, 1.58]} />
      <mesh geometry={nodes.defaultMaterial_cell005.geometry} material={materials.material_1} position={[-4.151, 7.629, 1.829]} />
      <mesh geometry={nodes.defaultMaterial_cell006.geometry} material={materials.material_1} position={[2.016, 15.145, -2.623]} />
      <mesh geometry={nodes.defaultMaterial_cell007.geometry} material={materials.material_1} position={[4.062, 1.909, -2.602]} />
      <mesh geometry={nodes.defaultMaterial_cell009.geometry} material={materials.material_1} position={[-4.113, 13.314, -0.431]} />
      <mesh geometry={nodes.defaultMaterial_cell010.geometry} material={materials.material_1} position={[3.274, 5.619, -3.846]} />
      <mesh geometry={nodes.defaultMaterial_cell012.geometry} material={materials.material_1} position={[-2.37, 13.939, -3.036]} />
      <mesh geometry={nodes.defaultMaterial_cell013.geometry} material={materials.material_1} position={[-2.695, 8.358, -4.139]} />
      <mesh geometry={nodes.defaultMaterial_cell014.geometry} material={materials.material_1} position={[3.603, 12.142, 2.978]} />
      <mesh geometry={nodes.defaultMaterial_cell015.geometry} material={materials.material_1} position={[-2.888, 1.648, 3.446]} />
      <mesh geometry={nodes.defaultMaterial_cell017.geometry} material={materials.material_1} position={[-4.398, 12.563, -1.85]} />
      <mesh geometry={nodes.defaultMaterial_cell018.geometry} material={materials.material_1} position={[2.548, 14.585, 2.258]} />
      <mesh geometry={nodes.defaultMaterial_cell020.geometry} material={materials.material_1} position={[-3.474, 1.078, 1.664]} />
      <mesh geometry={nodes.defaultMaterial_cell021.geometry} material={materials.material_1} position={[1.424, 1.337, 3.976]} />
      <mesh geometry={nodes.defaultMaterial_cell022.geometry} material={materials.material_1} position={[1.632, 0.739, 2.151]} />
      <mesh geometry={nodes.defaultMaterial_cell024.geometry} material={materials.material_1} position={[-2.148, 14.945, 2.243]} />
      <mesh geometry={nodes.defaultMaterial_cell025.geometry} material={materials.material_1} position={[1.674, 16.018, 2.591]} />
      <mesh geometry={nodes.defaultMaterial_cell026.geometry} material={materials.material_1} position={[-0.427, 0.762, 3.109]} />
      <mesh geometry={nodes.defaultMaterial_cell027.geometry} material={materials.material_1} position={[-4.446, 1.736, -0.881]} />
      <mesh geometry={nodes.defaultMaterial_cell028.geometry} material={materials.material_1} position={[0.715, 0.82, -3.525]} />
      <mesh geometry={nodes.defaultMaterial_cell029.geometry} material={materials.material_1} position={[1.891, 0.732, -1.072]} />
      <mesh geometry={nodes.defaultMaterial_cell030.geometry} material={materials.material_1} position={[2.756, 1.588, 3.419]} />
      <mesh geometry={nodes.defaultMaterial_cell031.geometry} material={materials.material_1} position={[3.929, 13.81, -0.042]} />
      <mesh geometry={nodes.defaultMaterial_cell032.geometry} material={materials.material_1} position={[2.459, 12.523, 3.832]} />
      <mesh geometry={nodes.defaultMaterial_cell033.geometry} material={materials.material_1} position={[2.427, 13.21, -3.637]} />
      <mesh geometry={nodes.defaultMaterial_cell034.geometry} material={materials.material_1} position={[-4.035, 11.403, -2.819]} />
      <mesh geometry={nodes.defaultMaterial_cell035.geometry} material={materials.material_1} position={[-3.3, 0.754, -0.385]} />
      <mesh geometry={nodes.defaultMaterial_cell036.geometry} material={materials.material_1} position={[-1.553, 11.623, 4.376]} />
      <mesh geometry={nodes.defaultMaterial_cell037.geometry} material={materials.material_1} position={[4.758, 7.974, -1.216]} />
      <mesh geometry={nodes.defaultMaterial_cell039.geometry} material={materials.material_1} position={[3.871, 1.052, -1.372]} />
      <mesh geometry={nodes.defaultMaterial_cell040.geometry} material={materials.material_1} position={[-4.024, 13.509, 1.19]} />
      <mesh geometry={nodes.defaultMaterial_cell041.geometry} material={materials.material_1} position={[-0.948, 11.49, -4.673]} />
      <mesh geometry={nodes.defaultMaterial_cell042.geometry} material={materials.material_1} position={[-0.084, 13.02, 4.214]} />
      <mesh geometry={nodes.defaultMaterial_cell043.geometry} material={materials.material_1} position={[-4.054, 3.64, -3.032]} />
      <mesh geometry={nodes.defaultMaterial_cell044.geometry} material={materials.material_1} position={[0.144, 3.029, 4.744]} />
      <mesh geometry={nodes.defaultMaterial_cell045.geometry} material={materials.material_1} position={[-0.737, 13.677, -3.998]} />
      <mesh geometry={nodes.defaultMaterial_cell046.geometry} material={materials.material_1} position={[-4.417, 4.401, 1.852]} />
      <mesh geometry={nodes.defaultMaterial_cell048.geometry} material={materials.material_1} position={[4.717, 5.626, 1.091]} />
      <mesh geometry={nodes.defaultMaterial_cell049.geometry} material={materials.material_1} position={[5.026, 11.097, -0.644]} />
      <mesh geometry={nodes.defaultMaterial_cell051.geometry} material={materials.material_1} position={[4.811, 2.818, -0.948]} />
      <mesh geometry={nodes.defaultMaterial_cell053.geometry} material={materials.material_1} position={[-0.494, 7.338, -5.099]} />
      <mesh geometry={nodes.defaultMaterial_cell054.geometry} material={materials.material_1} position={[-0.107, 2.336, -4.935]} />
      <mesh geometry={nodes.defaultMaterial_cell055.geometry} material={materials.material_1} position={[-2.118, 13.453, 3.637]} />
      <mesh geometry={nodes.defaultMaterial_cell056.geometry} material={materials.material_1} position={[3.893, 11.89, -2.816]} />
      <mesh geometry={nodes.defaultMaterial_cell057.geometry} material={materials.material_1} position={[-2.793, 15.048, -1.764]} />
      <mesh geometry={nodes.defaultMaterial_cell058.geometry} material={materials.material_1} position={[-3.003, 15.321, 1.02]} />
      <mesh geometry={nodes.defaultMaterial_cell059.geometry} material={materials.material_1} position={[3.102, 15.003, 1.019]} />
      <mesh geometry={nodes.defaultMaterial_cell060.geometry} material={materials.material_1} position={[-0.924, 1.364, 4.168]} />
      <mesh geometry={nodes.defaultMaterial_cell061.geometry} material={materials.material_1} position={[1.509, 13.618, 3.717]} />
      <mesh geometry={nodes.defaultMaterial_cell062.geometry} material={materials.material_1} position={[-0.86, 14.805, 3.048]} />
      <mesh geometry={nodes.defaultMaterial_cell063.geometry} material={materials.material_1} position={[-1.789, 15.64, -2.657]} />
      <mesh geometry={nodes.defaultMaterial_cell064.geometry} material={materials.material_1} position={[-2.891, 1.163, -2.842]} />
      <mesh geometry={nodes.defaultMaterial_cell065.geometry} material={materials.material_1} position={[-0.737, 0.737, -0.173]} />
      <mesh geometry={nodes.defaultMaterial_cell066.geometry} material={materials.material_1} position={[-4.269, 6.502, -2.547]} />
      <mesh geometry={nodes.defaultMaterial_cell067.geometry} material={materials.material_1} position={[-3.782, 12.37, 2.18]} />
      <mesh geometry={nodes.defaultMaterial_cell068.geometry} material={materials.material_1} position={[1.765, 14.732, 2.758]} />
      <mesh geometry={nodes.defaultMaterial_cell070.geometry} material={materials.material_1} position={[-4.708, 10.222, -1.311]} />
      <mesh geometry={nodes.defaultMaterial_cell071.geometry} material={materials.material_1} position={[-2.333, 5.636, -4.386]} />
      <mesh geometry={nodes.defaultMaterial_cell072.geometry} material={materials.material_1} position={[1.721, 4.228, -4.755]} />
      <mesh geometry={nodes.defaultMaterial_cell074.geometry} material={materials.material_1} position={[-2.064, 2.147, -4.276]} />
      <mesh geometry={nodes.defaultMaterial_cell075.geometry} material={materials.material_1} position={[4.768, 9.348, 1.171]} />
      <mesh geometry={nodes.defaultMaterial_cell076.geometry} material={materials.material_1} position={[-0.733, 15.975, 2.932]} />
      <mesh geometry={nodes.defaultMaterial_cell077.geometry} material={materials.material_1} position={[2.128, 1.583, -4.184]} />
      <mesh geometry={nodes.defaultMaterial_cell078.geometry} material={materials.material_1} position={[-2.925, 16.155, -1.203]} />
      <mesh geometry={nodes.defaultMaterial_cell079.geometry} material={materials.material_1} position={[1.771, 8.25, -4.784]} />
      <mesh geometry={nodes.defaultMaterial_cell080.geometry} material={materials.material_1} position={[4.701, 4.195, -1.644]} />
      <mesh geometry={nodes.defaultMaterial_cell081.geometry} material={materials.material_1} position={[0.257, 15.763, -3.223]} />
      <mesh geometry={nodes.defaultMaterial_cell082.geometry} material={materials.material_1} position={[-3.069, 16.366, -0.357]} />
      <mesh geometry={nodes.defaultMaterial_cell083.geometry} material={materials.material_1} position={[0.036, 14.748, -3.441]} />
      <mesh geometry={nodes.defaultMaterial_cell084.geometry} material={materials.material_1} position={[3.538, 14.023, -1.734]} />
      <mesh geometry={nodes.defaultMaterial_cell085.geometry} material={materials.material_1} position={[1.265, 8.389, 4.239]} />
      <mesh geometry={nodes.defaultMaterial_cell086.geometry} material={materials.material_1} position={[4.857, 5.029, -1.049]} />
      <mesh geometry={nodes.defaultMaterial_cell087.geometry} material={materials.material_1} position={[-1.958, 16.138, 2.276]} />
      <mesh geometry={nodes.defaultMaterial_cell088.geometry} material={materials.material_1} position={[-3.842, 2.997, 2.681]} />
      <mesh geometry={nodes.defaultMaterial_cell089.geometry} material={materials.material_1} position={[3.202, 15.286, -0.743]} />
      <mesh geometry={nodes.defaultMaterial_cell091.geometry} material={materials.material_1} position={[2.626, 16.157, 1.421]} />
      <mesh geometry={nodes.defaultMaterial_cell094.geometry} material={materials.material_1} position={[0.544, 15.379, 3.019]} />
      <mesh geometry={nodes.defaultMaterial_cell096.geometry} material={materials.material_1} position={[-3.109, 15.499, -0.151]} />
      <mesh geometry={nodes.defaultMaterial_cell008.geometry} material={materials.material_1} position={[3.343, 3.873, 3.461]} />
      <mesh geometry={nodes.defaultMaterial_cell011.geometry} material={materials.material_1} position={[-2.936, 16.384, 0.786]} />
      <group position={[-15.785, 15.885, 11.653]}>
        <group scale={0.4}>
          <mesh geometry={nodes.Map07.geometry} material={materials.Meshmatcapmaterialpaper} rotation={[0, 0, 0.682]} />
        </group>
      </group>
      <group position={[-0.471, 1.491, 0.736]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.532, 0.868, 7.115]} rotation={[Math.PI / 2, 0, 0]} scale={7.915}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material_1} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.material} />
        </group>
      </group>
      <directionalLight intensity={5} decay={2} color="#fffaeb" position={[-13.409, 48.408, -0.96]} />
      <directionalLight intensity={5} decay={2} position={[8.558, 41.288, 25.153]} rotation={[-1.724, -0.007, 0.023]} scale={10.927} />
      <pointLight intensity={20} decay={2} color="#d2bdb1" position={[7.648, 13.877, 28.447]} rotation={[-2.318, 1.041, -2.644]} />
      <spotLight intensity={20} angle={0.7} penumbra={1} decay={2} position={[54.775, 73.158, -33.214]} rotation={[-1.923, 0.711, 3.048]} scale={[39.767, 102.189, 209.574]} />
    </group>
  )
}

useGLTF.preload('/breakingJar.glb')
